### ISSUE TITLE
Feature Request: hnrss.org/classic

### ISSUE THREAD

**Issue by edavis** [hnrss/hnrss#14]
@pageman on [Twitter](https://twitter.com/pageman/status/845479982017081350):

> HN has http://news.ycombinator.com/classic  - does HNRSS support this? Like: https://hnrss.org/classic 

Doesn't look like either Algolia or the Firebase API have this, so we're limited. But would be a pretty neat addition.

**Comment by alphapapa** [comment]
Did something change?  Because `/classic` looks no different than `/` to me.

**Comment by edavis** [comment]
@alphapapa Not sure I follow... `/classic` has never been available in hnrss.

**Comment by alphapapa** [comment]
I mean, http://news.ycombinator.com/classic looks no different than http://news.ycombinator.com/

**Comment by edavis** [comment]
Putting this on ice until Algolia and/or Firebase provide a way to grab /classic data

**Comment by edavis** [comment]
cc @alphapapa @Glowin

hnrss now supports /classic: https://hnrss.org/classic

**Comment by alphapapa** [comment]
@edavis Cool, but I still don't know what exactly https://news.ycombinator.com/classic is, because it looks the same as https://news.ycombinator.com/news to me.  What's the difference?  :)

**Comment by edavis** [comment]
@alphapapa Classic only counts votes from "early users" (accounts created before Feb 13, 2008) while News counts votes from all accounts.

Refs: https://github.com/minimaxir/hacker-news-undocumented#hacker-news-classic
