### ISSUE TITLE
Link preview

### ISSUE THREAD

**Issue by iamkarlson** [hnrss/hnrss#15]
Is it possible to add link preview like below

![image](https://cloud.githubusercontent.com/assets/4534374/24835575/f21ed228-1d16-11e7-9660-22e08775c0f9.png)

**Comment by edavis** [comment]
If someone can implement this, I'll take a look at the PR.

I'm not opposed in theory, I just can't think of a way of doing this that won't add a ton of complexity :(

**Comment by edavis** [comment]
Never came up with a way of doing this in a clean, succinct way.
