### ISSUE TITLE
"Ask HN" has no entry stats

### ISSUE THREAD

**Issue by vsund** [hnrss/hnrss#17]
Is it intentional that the entries for "Ask HN" have no stats like upvotes, comments and so on?
I don't know whether other categories have stats or not, just curious whether there's a reason for this :)

**Comment by edavis** [comment]
Hey @vsund — No conscious decision. Code just kind of evolved that way :)

If a "story_text" attribute is present in the search results, it has always been used verbatim for the `<description>` RSS element. If not, it got the upvotes, comments, etc. treatment.

I do suppose it makes some sense to unify this handling. I'll keep it on my radar.

**Comment by edavis** [comment]
This got fixed in the Go rewrite, so shouldn't be an issue anymore. Thanks again for the report!
