### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by narfman0** [hnrss/hnrss#18]
Filters would be brilliant - maybe regexs to filter content?

E.g. having 6 out of 7 uber articles for the last few weeks hurts my soul - I would frankly be happy to remove all .*uber.* articles, and plenty other "hacker" news.

Project looks rad thanks bunches!

**Comment by edavis** [comment]
Using `q=KEYWORD` (see "Search Feeds" on https://edavis.github.io/hnrss/) can get you a feed of just topics you're interested in, but it sounds more like you're looking for "mute" functionality to exclude certain keywords instead. Is that right?

I'll check into it. If it's only a few lines of code, might be worth adding.

**Comment by chmaynard** [comment]
There are a number of domains that I would like to filter out as I read HN. If I were to create such a list in a known location on my local machine or on your server, could HNRSS be modified to filter out all posts from the domains in this list?

**Comment by edavis** [comment]
Hey guys — You might want to check out http://hnapp.com/. It looks like it has better filtering options than hnrss.

@chmaynard Appears you could do something like `-host:abc.com -host:xyz.com` to accomplish this in hnapp. This would have to be duplicated in each feed which isn't ideal... but may not be much of an issue depending on how many feeds you have.

I may still add filtering functionality eventually to hnrss, but it gets tricky as I try to stay within the parameters of Algolia as much as possible. There's just not a lot of hooks available for excluding results, as best I can tell.

(cc @narfman0 @chmaynard @raquo)

**Comment by edavis** [comment]
Closing this as I'd like hnrss to just stay a slim wrapper on top of the Algolia HN API. I just don't think getting into this territory is a good fit.

Hopefully hnapp.com or some other service did the trick!
