### ISSUE TITLE
Should escape &lt; within code blocks

### ISSUE THREAD

**Issue by talklittle** [hnrss/hnrss#20]
https://news.ycombinator.com/item?id=15293578

The first code block is:

```
  $ dig crates.io @ns-a1.io +norecurse

  ; <<>> DiG 9.11.2 <<>> crates.io @ns-a1.io +norecurse
  ;; global options: +cmd
  ;; Got answer:
  ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18874
  ;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 3, 
  ADDITIONAL: 1

  ;; OPT PSEUDOSECTION:
  ; EDNS: version: 0, flags:; udp: 4096
  ;; QUESTION SECTION:
  ;crates.io.			IN	A

  ;; AUTHORITY SECTION:
  crates.io.		86400	IN	NS	dns3.easydns.ca.
  crates.io.		86400	IN	NS	dns1.easydns.com.
  crates.io.		86400	IN	NS	dns2.easydns.net.

  ;; Query time: 83 msec
  ;; SERVER: 194.0.1.1#53(194.0.1.1)
  ;; WHEN: Wed Sep 20 15:33:13 CEST 2017
  ;; MSG SIZE  rcvd: 127
```

But renders as:

<img width="328" alt="screen shot 2017-09-20 at 9 21 35 am" src="https://user-images.githubusercontent.com/87961/30655269-465f58ea-9de5-11e7-9c39-52b5ab248902.png">

**Comment by talklittle** [comment]
Whoops, problem with my newsreader, not hnrss. Sorry!

**Comment by edavis** [comment]
Hey @talklittle — Good catch. This should have stopped being an issue around September 2018 with the rewrite in Go. The `<description>` is CDATA now which should take care of issues like this.

Everything looks good to me when I pull this post up in News Explorer:

<img width="838" alt="Screen Shot 2020-10-25 at 7 41 38 PM" src="https://user-images.githubusercontent.com/622509/97128752-62ca6b00-16fa-11eb-9a18-2940f2f34e20.png">

Of course, let me know if you're still seeing issues or come across any in the future. Thanks!
