### ISSUE TITLE
Add feed for comments on thread by user

### ISSUE THREAD

**Issue by timvisee** [hnrss/hnrss#26]
I would like to have a feed for comments made in a thread of a specific user.

The replies feed lists comments on comments by a user, but not comments on a thread by a user.

Maybe the replies feed can be improved to include these as well?

**Comment by edavis** [comment]
Love this idea. Best of all, very doable via the Algolia HN API.

I can't promise an ETA but definitely on my todo list next time I'm hacking around on the code.

In case any intrepid developers are reading this and want to take a stab at building this, here's the Algolia query to use for this: https://hn.algolia.com/api/v1/search_by_date?tags=author_edavis,story_23778510,comment

**Comment by edavis** [comment]
Hey @timvisee!

This is ready on hnrss.org. I ended up modifying the "thread feed" by allowing an optional `author` parameter:

https://hnrss.org/item?id=23778510&author=edavis

Without `author` it just lists all the comments in the thread but by attaching `author` it'll filter to comments written by a particular user.

Let me know if anything doesn't look right to you. Thanks again for the suggestion!
