### ISSUE TITLE
Look into feed "recommendation" by validator

### ISSUE THREAD

**Issue by edavis** [hnrss/hnrss#29]
<img width="1917" alt="Screen Shot 2020-07-10 at 8 42 20 AM" src="https://user-images.githubusercontent.com/622509/87172660-6b04b480-c289-11ea-8e80-0680278af642.png">

Refs: <https://news.ycombinator.com/item?id=23779892>

**Comment by edavis** [comment]
Not immediately obvious what the fix would be and nobody has ever complained about their reader being broken without it... closing.

**Comment by somini** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhnrss.org%2Fnewest

This is valid now, no longer applies anyway.
