### ISSUE TITLE
Support /bestcomments

### ISSUE THREAD

**Issue by telotortium** [hnrss/hnrss#37]

**Comment by edavis** [comment]
Hello @telotortium!

A feed for /bestcomments is now available: https://hnrss.org/bestcomments

This is such a neat endpoint. I really like how this came out. Thanks a ton for the suggestion.

I'm going to let this burn in for a few days and if all looks good I'll update the hnrss.github.io docs officially announcing it.

**Comment by telotortium** [comment]
Thanks a lot @edavis! I'm testing it out now
