### ISSUE TITLE
User feed shows many titles as just ""

### ISSUE THREAD

**Issue by telotortium** [hnrss/hnrss#41]
For the past few days I'm seeing many entries in the users feed show the title of the Hacker News story in the item title as just `""`. For example, in the feed `https://hnrss.org/user?id=kibwen`, the feed now contains an entry like this:

```
<item>
<title>
<![CDATA[ New comment by kibwen in "" ]]>
</title>
<description>
<![CDATA[ <p>Are we leaping to conclusions by assuming this is referring to an impossible burger/beyond burger sort of product? A "plant-based" burger could also just be the sort of plain old veggie burger that e.g. Burger King has been offering for decades. Is there more detailed information somewhere?</p> ]]>
</description>
<pubDate>Mon, 09 Nov 2020 22:52:28 +0000</pubDate>
<link>https://news.ycombinator.com/item?id=25040947</link>
<dc:creator>kibwen</dc:creator>
<comments>https://news.ycombinator.com/item?id=25040947</comments>
<guid isPermaLink="false">https://news.ycombinator.com/item?id=25040947</guid>
</item>
```

**Comment by edavis** [comment]
@telotortium Thanks for the report! Sorry you ran into this.

As of right now the feed appears back to normal. Sometimes there's a hitch with Algolia and some data goes (temporarily) missing. But the ship usually gets back on course soon enough.

I'm going to close this for now but if it keeps happening I'll open this back up and see if there's anything hnrss can do to alleviate the issue.
