### ISSUE TITLE
JSON Feed author(s) field should be an object, not a string

### ISSUE THREAD

**Issue by NicolasLM** [hnrss/hnrss#43]
The JSON Feed [specification](https://jsonfeed.org/version/1.1) mentions that the `author` (v1.0) and `authors` (v1.1) fields should contain objects, for instance:

```json
{
    "author": {
        "name": "Brent Simmons",
        "url": "http://example.org/",
        "avatar": "https://example.org/avatar.png"
    }
}
```

The feed produced by hnrss.org uses `author` as a string:
```json
{
    "author":  "Brent Simmons"
}
```

**Comment by edavis** [comment]
This has been resolved on production (thanks @revett!)
