### ISSUE TITLE
Disable Description element

### ISSUE THREAD

**Issue by carlosflorencio** [hnrss/hnrss#49]
Hi,

The docs describe a way to disable the `description` tag but doesn't seem to work, example:
https://hnrss.org/best?description=0

The returned XML still contains the description tag, is this the expected behaviour?

Thanks

**Comment by edavis** [comment]
Yikes... nope, that's definitely wrong.

Thanks for the report. I'll try to find some time over the next few days to roll out a fix.

**Comment by edavis** [comment]
@carlosflorencio This issue has been resolved thanks to @revett

cc #63
