### ISSUE TITLE
Invalid search results erors from Algolia.

### ISSUE THREAD

**Issue by hopesthoughts** [hnrss/hnrss#56]
I'm not sure why it's happening, but whenever I try and perform a search, an error saying "Invalid JSON received from Algolia" happens.
    Here's a for instance:
https://hnrss.org/newest?q=windows
    PS, I hope I'm filing this in the right place.

**Comment by edavis** [comment]
Thanks for the heads up! I think there were some general issues with Algolia (the service that powers hnrss) right around when this was posted. Everything resolved on its own by the time I was aware, though.

At this point everything looks to be back up and running so I'm going to close this. But let me know if it starts acting up again for you.

(And, yeah, this place is fine for filing issues like this.)
