### ISSUE TITLE
Add option to exclude results with links to paywalled domains

### ISSUE THREAD

**Issue by svpn** [hnrss/hnrss#57]
Exclude results when link matches paywall domains in a text file where the binary runs.

_domains.txt_

```
paywall1.com
paywall2.com
paywall3.com
```

Not just paywalls, there are other reasons to exclude domains.

**Comment by edavis** [comment]
Just to clarify, you're saying this would be an optional feature for users who run a local instance of hnrss, right? Not the main hnrss.org service?

If so, I'm not immediately opposed to something like this... but to be honest it's going to be a low priority item for me.

I will definitely review any PR that comes my way, though.
