### ISSUE TITLE
RSS feed for Daily HN digest

### ISSUE THREAD

**Issue by jakubpawlowicz** [hnrss/hnrss#68]
Thanks for this cool project of yours!

Is there currently an endpoint I can reach to get a RSS feed of HN daily digest, i.e. https://news.ycombinator.com/front ?
I hope it'll help me lessen my load on what happens on HN :-)

Thanks,
Jakub

**Comment by edavis** [comment]
Hi Jakub,

Unfortunately, I don't think hnrss can accommodate you here.

BUT, I do have something that might work for you instead: https://www.daemonology.net/hn-daily/. And an RSS feed is available here: https://www.daemonology.net/hn-daily/index.rss

Good luck!

**Comment by jakubpawlowicz** [comment]
Thanks @edavis, much appreciated!
