### ISSUE TITLE
Rate Limit very aggressive

### ISSUE THREAD

**Issue by christian-bromann** [hnrss/hnrss#71]
I would be nice if we could reduce the rate limit a little bit. Currently it is very aggressive and makes the service not much useable.

**Comment by edavis** [comment]
The global rate limit is 6 requests per minute along with a specialized rate limit of 1 request per minute for two particularly aggressive crawlers.

If you're getting caught up in the specialized rate limit, apologies for the inconvenience but I had to do it to keep the service up and available for everyone.

FWIW, all hnrss outputs are cached for 5 minutes at a time so any requests more often than that are redundant.

**Comment by christian-bromann** [comment]
Thanks for the info.
