### ISSUE TITLE
using 'count'  with Search Parameter not working 

### ISSUE THREAD

**Issue by abtxu** [hnrss/hnrss#72]
For instance,
https://hnrss.org/newest?q=WordPress?count=50
not working at all:
There are no unread articles in your Feedly.

**Comment by edavis** [comment]
Hi @abtxu,

Change that second question mark to an ampersand: https://hnrss.org/newest?q=WordPress&count=50

(This is my fault. I never explicitly mention in the docs how to combine filters.)
