### ISSUE TITLE
Count param not working with user's favorite stories

### ISSUE THREAD

**Issue by ysftaha** [hnrss/hnrss#75]
I use favorite stories introduced in https://github.com/hnrss/hnrss/commit/6aae41ee43ca965e366cd74a56d7b050bbd757a3 combining this with a count does not work. 

example:
https://hnrss.org/favorites?count=99&id=Ghoyome

seems to be capped at 30

**Comment by ysftaha** [comment]
might be related to #69

**Comment by edavis** [comment]
Hi @ysftaha — Thanks for the report.

I explain a bit why this happens in #51.

See also: hnrss/hnrss.github.io#4
