### ISSUE TITLE
Rate limit?

### ISSUE THREAD

**Issue by paulchartres** [hnrss/hnrss#76]
Hi there,
I created a Jetbrain Space extension (https://plugins.jetbrains.com/plugin/20337-rsspace) that allows users to connect to RSS feeds. My application polls the feeds once every ten seconds to check for new content, but it seems like after a few requests, my network just no longer has access to the website.
Is there some kind of rate limit? If so, should I reduce the amount of polling requests I make, or can I apply to get my network IP whitelisted?
Thanks a lot.

**Comment by edavis** [comment]
Hi Paul,

Yes, there is a rate limit. Please reduce your polling interval. Inspect the `Expires` header for how often new content will be available.
