### ISSUE TITLE
Frontpage Feed Isn't Updating

### ISSUE THREAD

**Issue by joereinhard** [hnrss/hnrss#77]
I'm subscribed to the frontpage feed and I haven't gotten updates for the past day or so.

**Comment by ggreenway** [comment]
+1 same for me. I get a valid RSS response from the server; it just isn't updating from some frozen point in time about a day ago. Cache-expiry is updating, but not the content.

**Comment by ggreenway** [comment]
I built and ran this repo, and it returns the same stale results as hnrss.org. This makes me think there's an issue with the data coming from the HN API, or the data is not what is expected so it isn't parsed correctly.

**Comment by davidstoker** [comment]
Starting looking through here a bit myself after seeing the feed stop. Looks like this depends upon Algolia for frontpage results and there's this issue reported over there: https://github.com/algolia/hn-search/issues/233

**Comment by edavis** [comment]
Hey all,

Yeah, unfortunately, hnrss is entirely dependent on the HN Search API (https://hn.algolia.com/api) for generating its feeds. Until Algolia gets the crawler running again, not much can be done. The crawler has gone down before, but this looks like the longest outage in quite some time.

To assist any future debuggers: I include a `X-Algolia-URL` header with every HTTP response that points to the API endpoint used to obtain the raw data. You can monitor this URL to see if a particular hnrss issue is Algolia returning stale data, or something else.

**Comment by ntns** [comment]
Seems Algolia is working on fixing the issue https://news.ycombinator.com/item?id=33790811

**Comment by davidstoker** [comment]
Looks like things are working again 👍🏻

**Comment by edavis** [comment]
Yep, looking much better. Closing for now. Feel free to re-open, if needed. I do want to flag one thing, though:

It looks like comments posted during the outage are not (yet?) appearing in the HN Search API results. Maybe they'll appear later, or maybe not.

If they don't appear, `/newcomments?q=TERM` will have a gap between 2022-11-28T04:59:46.000Z to whenever the crawler started working again. Just FYI.
