### ISSUE TITLE
Can I donate to you regularly on patreon?

### ISSUE THREAD

**Issue by huggsboson** [hnrss/hnrss#82]
I just realized the newsyc100 bot on twitter that was feeding nitter that was feeding my RSS reader had died.  I noticed that you had replied to one of my pleas for help on hn with hnrss, which is now working great for me.  Any chance you can include a patreon link on your main page so I can send you some monthly money?  $5 a month to help defray costs?

**Comment by osantana** [comment]
I would like to sponsor the project (or developers). Is it possible?

**Comment by edavis** [comment]
Hi @huggsboson and @osantana,

There are no current plans for a hnrss Patreon. The offers are greatly appreciated, though!

**Comment by osantana** [comment]
If you change your mind and plan to accept contributions for your useful service/code, just reopen the issue.
