### ISSUE TITLE
Every pubDate is now set to now()

### ISSUE THREAD

**Issue by stevenirby** [hnrss/hnrss#92]
Before the pubDate worked as expected and would be the date when someone left a comment. Something has changed and the pubDate is the now() date.

- go to a users comments: https://hnrss.org/replies?id=tptacek
- look at the pubDate
- you can clearly see it's the same date for now for all entries

Maybe something on the algolia side?

**Comment by markcellus** [comment]
Yeah open RSS feeds are showing the same date as well in the feed I just generated

https://openrss.org/news.ycombinator.com/threads?id=tptacek

Doesnt look like its a now timestamp though. Looks like the user just posted those recent posts on the same day.

**Comment by jerrinot** [comment]
this PR is aiming to fix it: https://github.com/hnrss/hnrss/pull/91

**Comment by edavis** [comment]
Thanks everybody for the reports. This should be fixed now. I know Algolia has been doing some work on their side (https://news.ycombinator.com/item?id=37821821) so I imagine this was related to that.

Closing for now but feel free to re-open if `created_at` / `pubDate` goes wonky again.
