### ISSUE TITLE
The best feed is empty

### ISSUE THREAD

**Issue by WestXu** [hnrss/hnrss#93]
https://hnrss.org/best

<img width="834" alt="image" src="https://github.com/hnrss/hnrss/assets/25974092/90635c36-021a-4f76-aa35-b5be6eba4175">

It's been like this for around 4 days.

**Comment by edavis** [comment]
Thanks for the report. At first glance, it looks like Algolia has disabled the feature on their end I was using to make this work.

It could be a temporary issue related to their recent upgrades (https://news.ycombinator.com/item?id=37821821) or they may have retired this completely.

I'll dig into this and update this issue once I know more.

**Comment by WestXu** [comment]
It is. So it was a problem on hn side. Feel free to close this one.

**Comment by jeffrey-slentz-algolia** [comment]
Hey @edavis what feature were you using? There were a lot of changes and it's likely we could have missed something :)

**Comment by edavis** [comment]
Hi @jeffrey-slentz-algolia — in this particular case, /best is built by fetching:

```
https://hn.algolia.com/api/v1/search_by_date?hitsPerPage=30&restrictSearchableAttributes=title&tags=(story,poll),(story_37926849,story_37939269,story_37955264,story_37965142,story_37949656,story_37938636,story_37927344,story_37950952,story_37938183,story_37931383,story_37941075,story_37931373,story_37943843,story_37957152,story_37938866,story_37929338,story_37956714,story_37952719,story_37955600,story_37955402,story_37943931,story_37946017,story_37947772,story_37958473,story_37960941,story_37964153,story_37959540,story_37937451,story_37961166,story_37931424)
```

with that list of story IDs first scraped from https://news.ycombinator.com/best.

More generally and off the top of my head, hnrss uses the following tags (story, poll, front_page, comment, ask_hn, show_hn, job, author_X, story_X) and the following filters (parent_id, objectID).

**Comment by edavis** [comment]
Thanks @jeffrey-slentz-algolia. Yeah, it seemed to be caused by missing `story_x` tags but they're back now so everything looks good here.

Appreciate the offer and, likewise, feel free to reach out if hnrss ever starts causing any problems on your end. I do my best to reduce the load as much as possible where I can, but you know how it goes.
